name: Build and Package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

jobs:
  package-windows:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          os: Windows-2019,
          build_arch: Win32,
          build_type: Debug
        }
        - {
          os: Windows-2019,
          build_arch: Win32,
          build_type: Release
        }
        - {
          os: Windows-2019,
          build_arch: x64,
          build_type: Debug
        }
        - {
          os: Windows-2019,
          build_arch: x64,
          build_type: Release
        }
        - {
          os: Ubuntu-18.04,
          build_arch: x64,
          build_type: Debug
        }
        - {
          os: Ubuntu-18.04,
          build_arch: x64,
          build_type: Release
        }
        - {
          os: Macos-10.15,
          build_arch: x64,
          build_type: Debug
        }
        - {
          os: Macos-10.15,
          build_arch: x64,
          build_type: Release
        }
    runs-on: ${{ matrix.config.os }}
    steps:

      - uses: actions/checkout@v1

      - name: Generate Win${{ matrix.config.build_arch }} ${{ matrix.config.build_type }}
        run: |
          cmake -S . -B Build -A ${{ matrix.config.build_arch }}

      - name: Build Win${{ matrix.config.build_arch }} ${{ matrix.config.build_type }}
        run: |
          cmake -S . -B Build --build --config ${{ matrix.config.build_type }}

      - uses: actions/upload-artifact@v2
        with:
          name: esd Win${{ matrix.config.build_arch }} ${{ matrix.config.build_type }} ${{ matrix.config.os }}
          path: |
            Build/{{ $matrix.config.build_type }}/**
          if-no-files-found: error
          retention-days: 7