name: Build and Package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          os: Windows-2019,
          build_arch: Win32,
          build_type: Debug,
          build_generator: Visual Studio 16 2019
        }
        - {
          os: Windows-2019,
          build_arch: Win32,
          build_type: Release,
          build_generator: Visual Studio 16 2019
        }
        - {
          os: Windows-2019,
          build_arch: x64,
          build_type: Debug,
          build_generator: Visual Studio 16 2019
        }
        - {
          os: Windows-2019,
          build_arch: x64,
          build_type: Release,
          build_generator: Visual Studio 16 2019
        }
        - {
          os: Ubuntu-18.04,
          build_arch: x64,
          build_type: Debug,
          build_generator: Ninja
        }
        - {
          os: Ubuntu-18.04,
          build_arch: x64,
          build_type: Release,
          build_generator: Ninja
        }
        - {
          os: Macos-10.15,
          build_arch: x64,
          build_type: Debug,
          build_generator: Ninja
        }
        - {
          os: Macos-10.15,
          build_arch: x64,
          build_type: Release,
          build_generator: Ninja
        }
    runs-on: ${{ matrix.config.os }}
    steps:

      - uses: actions/checkout@v1

      - name: Install Ninja
        if: "contains(matrix.config.os, 'Macos')"
        run: |
          brew install ninja

      - name: Install Ninja
        if: "contains(matrix.config.os, 'Ubuntu')"
        run: |
          sudo apt-get install ninja-build

      - name: Generate ${{ matrix.config.os }}-${{ matrix.config.build_arch }} ${{ matrix.config.build_type }}
        if: "contains(matrix.config.build_generator, 'Visual Studio')"
        run: |
          cmake -S . -B Build -A ${{ matrix.config.build_arch }} -G "${{ matrix.config.build_generator}}"

      - name: Generate ${{ matrix.config.os }}-${{ matrix.config.build_arch }} ${{ matrix.config.build_type }}
        if: "!contains(matrix.config.build_generator, 'Visual Studio')"
        run: |
          cmake -S . -B Build -G "${{ matrix.config.build_generator}}"

      - name: Build ${{ matrix.config.os }}-${{ matrix.config.build_arch }} ${{ matrix.config.build_type }}
        run: |
          cmake --build Build --config ${{ matrix.config.build_type }}

      - uses: actions/upload-artifact@v2
        with:
          name: esd ${{ matrix.config.os }}-${{ matrix.config.build_arch }} ${{ matrix.config.build_type }} ${{ matrix.config.os }}
          path: |
            Build/${{ matrix.config.build_type }}/**
            Build/esd
          if-no-files-found: error
          retention-days: 7